### ISSUE TITLE
Image Overflowing Its Container In the About Page

### ISSUE THREAD

**Issue by eniolajayi** [zuri-training/e-care-fe-pjt-6#16]
@ibrahimbank There is an image on the about page causing the viewport to overflow.

This Element 👇

```css
.details__empty::before {
    position: absolute;
    content: " ";
    width: 300px;
    height: 200px;
    top: -1rem;
    background: url(../assets/Image/about-page-img02.jpg) center top;
    background-size: cover;
}
```
This section. Everything else is ok  
![FireShot Capture 146 - E-Care About US - localhost](https://user-images.githubusercontent.com/62861035/123000453-850aaa80-d3a7-11eb-9d91-62f9e689f756.png)
